name: Dev Deployment

on:
  push:
    branches: ["master"]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install
      - name: Build app with .env
        run: |
          echo REACT_APP_API_BASE_URL=https://api.sunatmodern.co.id/ >> .env
          echo PORT=5002 >> .env
          npm run build
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./build/./"
          target: "/home/sunatmodern.co.id/tempdir"
      - name: copy package-lock.json to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "package-lock.json"
          target: "/home/sunatmodern.co.id"
  rebase-install:
    runs-on: ubuntu-latest
    needs: ci-build
    steps:
      - name: setup ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/sunatmodern.co.id/SunMod-Client
            rm -r build
            mv /home/sunatmodern.co.id/tempdir/build /home/sunatmodern.co.id/SunMod-Client
            cd /home/sunatmodern.co.id/SunMod-Client
            git checkout master
            git pull
            rm package-lock.json
            PATH="/root/.nvm/versions/node/v20.18.0/bin/:$PATH"
            npm install
            pm2 restart sumod-client
            exit
  move-package-lock:
    runs-on: ubuntu-latest
    needs: rebase-install
    steps:
      - name: setup ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/sunatmodern.co.id/SunMod-Client
            rm package-lock.json
            cd /home/sunatmodern.co.id
            mv package-lock.json /home/sunatmodern.co.id/SunMod-Client
