name: Contabo Deployment

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /home/sunatmodern.co.id/SunMod-Client
            git pull
            mv /home/sunatmodern.co.id/build /home/sunatmodern.co.id/SunMod-Client
            PATH="/root/.nvm/versions/node/v20.18.0/bin/:$PATH"
            npm install
            npm run build
            pm2 restart sumod-client
            
